config/routes.rb
Rails.application.routes.draw do
  root to: "architects#index"

  resources :buildings
  resources :architects
  resources :image

  get 'search/multisearch'
  get 'buildings/:id/versions', to: 'buildings#show_versions', as: 'building_versions'
  get "/users/admin" => "admin#index"
  post "/users/admin" => "admin#update"

  devise_for :users
end

app/models/architect.rb
class Architect < ApplicationRecord
  has_many :buildings, -> { order :address1 }
  include PgSearch
  multisearchable against: [:name, :description]

  def prev
    Architect.where("id < ?", id).order("id desc").first || Architect.last
  end

  def next
    Architect.where("id > ?", id).first || Architect.first
  end
end

app/controllers/architects_controller.rb
require "redcarpet"

class ArchitectsController < ApplicationController
  before_action :set_architect, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /architects
  # GET /architects.json
  def index
    @architects = Architect.all.order("name asc")
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @architects, each_serializer: Architects::IndexSerializer }
    end
  end

  # GET /architects/1
  # GET /architects/1.json
  def show
    if @architect.description.nil?
      @description = ""
    else
      renderer = Redcarpet::Render::HTML.new(filter_html: true)
      markdown = Redcarpet::Markdown.new(renderer)
      @description = markdown.render(@architect.description)
    end
  end

  # GET /architects/new
  def new
    @architect = Architect.new
  end

  # GET /architects/1/edit
  def edit
  end

  # POST /architects
  # POST /architects.json
  def create
    @architect = Architect.new(architect_params)

    respond_to do |format|
      if @architect.save
        format.html { redirect_to @architect, notice: 'Architect was successfully created.' }
        format.json { render :show, status: :created, location: @architect }
      else
        format.html { render :new }
        format.json { render json: @architect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /architects/1
  # PATCH/PUT /architects/1.json
  def update
    respond_to do |format|
      if @architect.update(architect_params)
        format.html { redirect_to @architect, notice: 'Architect was successfully updated.' }
        format.json { render :show, status: :ok, location: @architect }
      else
        format.html { render :edit }
        format.json { render json: @architect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /architects/1
  # DELETE /architects/1.json
  def destroy
    @architect.destroy
    respond_to do |format|
      format.html { redirect_to architects_url, notice: 'Architect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_architect
      @architect = Architect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def architect_params
      params.require(:architect).permit(:name, :description)
    end
end

app/helpers/architects_helper.rb
module ArchitectsHelper
  def next_architect_link(architect)
    link_to "next", architect.next
  end

  def prev_architect_link(architect)
    link_to "previous", architect.prev
  end
end

app/views/architects/_form.html.erb
<%= form_with(model: architect, local: true) do |form| %>
  <% if architect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(architect.errors.count, "error") %> prohibited this architect from being saved:</h2>

      <ul>
      <% architect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :name %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :name, id: :architect_name %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :description %>
      <p>(Format text using <a href='https://daringfireball.net/projects/markdown/basics'>markdown</a>)</p>
    </div>
    <div class='col-sm-10'>
      <%= form.text_area :description, id: :architect_description %>
    </div>
  </div>

  <div class="field">
  </div>

  <div class="field">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/architects/edit.html.erb
<h1>Edit Architect</h1>

<%= render 'form', architect: @architect %>

<%= link_to 'Show', @architect %> |
<%= link_to 'Back', architect_path(@architect) %>

app/views/architects/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-sm-6 building-title'>
    Sacramento Architects
  </div>
  <div class='col-sm-6 text-right'>
    <%= form_tag '/search/multisearch', method: :get  do %>
      <%= text_field_tag "search_text" %>
      <%= submit_tag "search" %>
    <% end %>
  </div>
</div>


<table>
  <tbody>
    <% @architects.each do |architect| %>
      <tr>
        <td><%= link_to architect.name, architect %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Architect', new_architect_path %>
<% end %>

app/views/architects/new.html.erb
<h1>New Architect</h1>

<%= render 'form', architect: @architect %>

<%= link_to 'Back', architects_path %>

app/views/architects/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row prev-next'>
  <div class='col-sm-4'>
    <%= prev_architect_link @architect %>
  </div>
  <div class='col-sm-4 text-center'>
    <%= link_to 'Back to architect list', architects_path %>
  </div>
  <div class='col-sm-4 text-right'>
    <%= next_architect_link @architect %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-12 building-title'>
    <%= @architect.name %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-12 architect-description'>
    <%= @description.html_safe %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    Buildings:
  </div>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <ul>
      <% @architect.buildings.each do |building| %>
        <li>
          <%= link_to building.address, building %>
          <%= first_thumbnail_tag(building) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to "Edit '#{@architect.name}'", edit_architect_path(@architect) %> |
  <%= link_to 'New Building', new_building_path(architect_id: @architect.id) %> |
  <%= link_to "Delete '#{@architect.name}'", @architect, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>