config/routes.rb
Rails.application.routes.draw do
  root to: "architects#index"

  resources :buildings
  resources :architects
  resources :image

  get 'search/multisearch'
  get 'buildings/:id/versions', to: 'buildings#show_versions', as: 'building_versions'
  get "/users/admin" => "admin#index"
  post "/users/admin" => "admin#update"

  devise_for :users
end

app/models/building.rb
class Building < ApplicationRecord
  has_paper_trail
  belongs_to :architect
  has_many :images

  # geocoded_by :address
  # after_validation :geocode
  include PgSearch
  multisearchable against: [:address1, :apn, :family, :notes]

  def address
    "#{address1}, #{city} #{zip}"
  end

  def needs_geocoding?
    latitude.nil? || longitude.nil?
  end

  def map_center
    [latitude, longitude].join(',')
  end

  def has_address?
    !(address1&.empty? || city&.empty? || zip&.empty?)
  end

  def prev
    architect.buildings.where("id < ?", id).order("id desc").first || architect.buildings.last
  end

  def next
    architect.buildings.where("id > ?", id).order("id asc").first || architect.buildings.first
  end
end

app/controllers/buildings_controller.rb
require "redcarpet"

class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy, :show_versions]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    if params[:version]
      @version_id = params[:version]
      @building = PaperTrail::Version.find(@version_id).reify
    end

    renderer = Redcarpet::Render::HTML.new(filter_html: true)
    markdown = Redcarpet::Markdown.new(renderer)
    @description = markdown.render(@building.description).html_safe if @building.description
  end

  def show_versions
  end

  def show_versions
  end

  # GET /buildings/new
  def new
    @architect = Architect.find params[:architect_id]
    @building = Building.new architect: @architect
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    delete_images
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_images
    image_param_keys = params["building"].keys.select { |key| key.include? "remove_image_" }
    image_param_keys.each do |key|
      image_id = image_id_from_param_key key
      if params["building"][key] == "1"
        image = Image.find image_id
        image.remove_filename!
        image.destroy
      end
    end
  end

  private

  def image_id_from_param_key(key)
    matches = /remove_image_(\d+)/.match(key)
    matches[1]
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:architect_id, :apn, :year, :address1, :building_type, :building_id, :city, :zip, :family, :type, :status, :source, :notes, :gsv, :key, :description)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
  def next_building_link(building)
    link_to "next", building.next
  end

  def prev_building_link(building)
    link_to "previous", building.prev
  end

  def google_static_map(center)
    image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=300x300&zoom=17&markers=#{center}"
  end

  def google_embedded_map_via_coords(building)
    iframe = <<-IFRAME
     <iframe width="390" height="330" frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=#{api_key}&q=#{building.map_center}"
      allowfullscreen>
     </iframe>
    IFRAME
    iframe.html_safe
  end

  def google_embedded_map(building)
    iframe = <<-IFRAME
     <iframe width="390" height="320" frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=#{ENV['GOOGLE_MAP_API_KEY']}&q=#{building.address}"
      allowfullscreen>
     </iframe>
    IFRAME
    iframe.html_safe
  end

  def embedded_map_tag(building)
    if building.has_address?
      google_embedded_map(building)
    else
      "This building needs an address".html_safe
    end
  end

  def static_map_tag(building)
    if building.needs_geocoding?
      "Sorry, no map available for this building yet."
    else
      google_static_map(building)
    end
  end

  def api_key
    ENV['GOOGLE_MAP_API_KEY']
  end

  def google_street_view_url(building)
    "https://maps.googleapis.com/maps/api/streetview?size=390x330&location=#{building.address}&key=#{api_key}".html_safe
  end

  def google_street_view_tag(building)
    image_tag google_street_view_url(building)
  end

  def building_versions_link(building)
    versions = building.versions
    if versions.count > 0
      link_to 'Show versions', building_versions_path(building)
    end
  end

  def showing_older_version?(version_id = @version_id)
    !!version_id
  end
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
        <% building.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row">
    <div class='col-sm-2'>
      Architect
    </div>
    <div class='col-sm-10'>
      <%= form.hidden_field :architect_id, value: building.architect_id %>
      <%= building.architect.name %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      Description
    </div>
    <div class='col-sm-10'>
      <%= form.text_area :description, id: :building_description %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      APN
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :apn, id: :building_apn %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :year %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :year, id: :building_year %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :address1 %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :address1, id: :building_address1 %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :city %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :city, id: :building_city %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :zip %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :zip, id: :building_zip %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label "Family / Business" %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :family, id: :building_family %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :building_type %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :building_type, id: :building_type %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :status %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :status, id: :building_status %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label :source %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :source, id: :building_source %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      GSV
    </div>
    <div class='col-sm-10'>
      <%= form.text_field :gsv, id: :building_gsv %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      <%= form.label "Notes / Builder / Construction" %>
    </div>
    <div class='col-sm-10'>
      <%= form.text_area :notes, id: :building_notes %>
    </div>
  </div>

  <div class="field row">
    <div class='col-sm-2'>
      Delete Images
    </div>
    <div class="col-sm-10">
      <% @building.images.each do |image| %>
        <div>
          <%= form.check_box "remove_image_#{image.id}" %>
          <img src="<%= image.path %>" class="building-image half-size" />
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Edit Building <%= @building.family %></h1>

<%= render 'form', building: @building %>

<div class='bottom-nav-links'>
  <%= link_to 'Add photo', new_image_path(building_id: @building.id), data: { turbolinks: false } %> |
  <%= link_to 'Show', @building %> |
  <%= link_to "Back to #{@building.architect.name}", architect_path(@building.architect) %>
</div>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <div><a href="/architects">architects</a></div>
</div>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Architect</th>
      <th>Apn</th>
      <th>Year</th>
      <th>Address1</th>
      <th>City</th>
      <th>Zip</th>
      <th>Family</th>
      <th>Type</th>
      <th>Status</th>
      <th>Source</th>
      <th>Notes</th>
      <th>google street view</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.architect_id %></td>
        <td><%= building.apn %></td>
        <td><%= building.year %></td>
        <td><%= building.address1 %></td>
        <td><%= building.city %></td>
        <td><%= building.zip %></td>
        <td><%= building.family %></td>
        <td><%= building.building_type %></td>
        <td><%= building.status %></td>
        <td><%= building.source %></td>
        <td><%= building.notes %></td>
        <td><%= building.gsv %></td>
        <td><%= building.key %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Delete', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', architect_path(@building.architect) %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<% if showing_older_version? %>
  <p id="notify_previous_version">Showing a previous version</p>
<% end %>

<div class='row prev-next'>
  <div class='col-sm-6'>
    <%= prev_building_link @building %>
  </div>
  <div class='col-sm-6 text-right'>
    <%= next_building_link @building %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-12 building-title'>
    <%= @building.family %>
  </div>
</div>


<div class='building-architect row'>
  <div class='col-sm-12'>
    <%= link_to @building.architect.name, @building.architect %>, <%= @building.year %>
  </div>
</div>

<div class='building-description row'>
  <div class='col-sm-12'>
    <%= @description %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-7'>


    <div class='building-architect row'>
      <div class='col-sm-10'>
        <% if @building.images.empty? %>
          <%= google_street_view_tag(@building) %>
        <% else %>
          <% @building.images.each do |image| %>
            <img src="<%= image.path_for_size(500) %>" class="building-image" />
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

  <div class='col-sm-5'>
    <div class='row'>
      <% if Rails.env.development? %>
          <div class='google-map-placeholder-dev'></div>
        <% else %>
        <div class='map'>
          <% if !@building.images.empty? %>
            <%= google_street_view_tag(@building) %>
          <% end %>
          <%= embedded_map_tag(@building) %>
        </div>
      <% end %>
    </div>
    <div class='row'>
      <div class='building-details'>
        <div class='row'>
          <div class='col-sm-6'>
            <%= @building.year %>
          </div>
          <div class='col-sm-6'>
            <%= @building.status %>
          </div>
        </div>

        <div class='row'>
          <div class='col-sm-12'>
          <%= @building.address %>
        </div>
        </div>

        <div class='row'>
          <div class='col-sm-12'>
            APN: <%= @building.apn %>
          </div>
        </div>

        <div class='row'>
          <div class='col-sm-12'>
          Notes: <%= @building.notes %>
        </div>
        </div>

        <div class='row'>
          <div class='col-sm-12'>
          Source: <%= @building.source %>
        </div>
      </div>

    </div>
    </div>
  </div>
</div>

<p>
  <strong>Type:</strong>
  <%= @building.building_type %>
</p>

<% if user_signed_in? %>
  <p>
  <%= link_to 'Edit building', edit_building_path(@building) %><br>
  <%= building_versions_link(@building) %>
  </p>
<% end %>

app/views/buildings/show_version.html.erb
<p id="notice"><%= notice %></p>

<div class='building-architect row'>
  <div class='col-sm-12'>
    <%= link_to @building.architect.name, @building.architect %>, <%= @building.year %>
  </div>
</div>

<div class='building-architect row'>
  <div class='col-sm-12'>
    <% @building.versions.each do |version| %>
      <div class='row'>
      <div class='col-sm-2'>
        <%= version.paper_trail_originator %>
        <%= version.whodunnit %>
      </div>
      <div class='col-sm-2'>
        <%= version.event %>
      </div>
      </div>
    <% end %>
  </div>
</div>


<% if user_signed_in? %>
  <p>
  <%= link_to 'Edit building', edit_building_path(@building) %><br>
  <%= link_to 'Back to building', building_path(@building) %>
  </p>
<% end %>

app/views/buildings/show_versions.html.erb
<p id="notice"><%= notice %></p>

<div class='building-architect row'>
  <div class='col-sm-12'>
    <%= link_to @building.architect.name, @building.architect %>, <%= @building.year %>
  </div>
</div>

<div class='building-architect row'>
  <div class='col-sm-12'>
    <% @building.versions.each do |version| %>
      <div class='row'>
        <div class='col-sm-2'>
          <%= link_to 'Show', building_path(@building, {version: version.id} ) %>
        </div>
        <div class='col-sm-2'>
          <%= version.whodunnit %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<% if user_signed_in? %>
  <p>
  <%= link_to 'Edit building', edit_building_path(@building) %><br>
  <%= link_to 'Back to building', building_path(@building) %>
  </p>
<% end %>